Areas/C_Area/Models/Product.cs
using System.ComponentModel.DataAnnotations;

namespace C_Area.Areas.C_Area.Models
{
    public class Product
    {
        [Key]
        public int ProductId { get; set; }
        public string? Name { get; set; }
        public string? Description { get; set; }
        public string? Image { get; set; }
        public double Price { get; set; }
        public int LabelId { get; set; }
        public bool IsActive { get; set; }
        public string? Category { get; set; }
    }
    public class Label
    {
        [Key]
        public int LabelId { get; set; }
        public string? LabelName { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace C_Area.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Areas/C_Area/Controllers/ShopsController.cs
using System.Reflection.Metadata;
using C_Area.Areas.C_Area.Data;
using C_Area.Areas.C_Area.Models;
using C_Area.Areas.C_Area.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace C_Area.Areas.C_Area.Controllers
{
    [Area("C_Area")]
    [Route("C_Area/[Controller]/[Action]")]
    [Route("C_Area/[Controller]")]
    
    public class ShopsController : Controller
    {
        private readonly C_AreaDbContext _context;

        public ShopsController(C_AreaDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> ShopIndex()
        {

            {
                ViewBag.LabelList = _context.Label.Select(x => new SelectListItem
                {

                    Value = x.LabelId.ToString(),
                    Text = x.LabelName

                }).ToList();

                return View();
            }   
         
        }
        [HttpPost]
        public async Task<IActionResult>ShopCreate(ProductVM product)
        {
            //file upload start
            string uniqueFileName = null;
            if (product.UploadImage !=null)
            {
               
                string uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Images");
                uniqueFileName = Guid.NewGuid().ToString()+"_"+product.UploadImage.FileName;

                string filepath = Path.Combine(uploadsFolder, uniqueFileName);

                if (!Directory.Exists(filepath))
                {
                    Directory.CreateDirectory(uploadsFolder);
                }
                using (var filestrem = new FileStream(filepath,FileMode.Create))
                {
                    await product.UploadImage.CopyToAsync(filestrem);
                }

            }
            //file upload end

            var RealDataModel = new Product();

            RealDataModel.Name = product.Name;
            RealDataModel.Price = product.Price;
            RealDataModel.Description = product.Description;
            RealDataModel.Category = product.Category;
            RealDataModel.LabelId = product.LabelId;
            RealDataModel.Image = uniqueFileName;

            _context.Product.Add(RealDataModel);
            _context.SaveChanges();

            return View("ShopIndex");
        }

        public async Task<IActionResult> ShopList()
        {
           var Data = _context.Product.ToList();

            return View(Data);
        }

        public IActionResult ShopInfo(int? id)
        {

            if (id == null)

                return NotFound();

            var Blog = _context.Product.FirstOrDefault(shop => shop.ProductId == id);

            return View("ShopIndex");
        }

        public async Task<IActionResult> ShopEdit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<IActionResult> ShopEdit(int id, [Bind("ProductId,Name,Description,Image,Price,LableId,IsActive,Category")] Product product)
        //{
        //    if (id != product.ProductId)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(product);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!ProductExist(product.ProductId))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction("ShopIndex");
        //    }
        //    return View(product);
        //}


     
        

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Admin/Shop/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Product.FindAsync(id);
            if (product != null)
            {
                _context.Product.Remove(product);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Labels()
        {
            var LebelList = _context.Label.ToList();

            return View(LebelList);
        }

        public IActionResult LabelCreate(Label model)
        {
            _context.Label.Add(model);

            try
            {
                _context.SaveChanges();
                return Json(true);
            }
            catch (Exception)
            {
                return Json(false);
            }



        }

        public IActionResult LabelEdit(int? id)
        {
            if (id == null)
                return NotFound();

            var Furnituredata = _context.Label.FirstOrDefault(Furniture => Furniture.LabelId == id);
            return View(Furnituredata);
        }

        [HttpPost]
        public IActionResult LabelEdit(Label Furnituredata)
        {
            if (Furnituredata.LabelName != null )
            {
                _context.Update(Furnituredata);
                _context.SaveChanges();
            }
            return RedirectToAction("Labels");
        }

        public IActionResult LabelDelete(int? id)

        {
            if (id == null)
                return NotFound();

            var Furnituredata = _context.Label.FirstOrDefault(Furniture => Furniture.LabelId == id);

            if (Furnituredata == null)
                return NotFound();

            _context.Remove(Furnituredata);
            _context.SaveChanges();

            return RedirectToAction("Labels");


        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using C_Area.Models;
using Microsoft.AspNetCore.Mvc;

namespace C_Area.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
         public IActionResult Admin()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Areas/C_Area/Views/Shops/Labels.cshtml
﻿@{
    ViewData["Title"] = "Labels";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@model IEnumerable<C_Area.Areas.C_Area.Models.Label>


<div class="row">
    <div class="col-md-12">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Label List</h3>
                <div class="card-tools">

                    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#createLabelModal">
                        <i class="fas fa-plus"></i> Add New Label
                    </button>



                </div>
            </div>
            <!-- /.card-header -->

            <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Label Name</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            foreach (var label in Model)
                            {
                                <tr>
                                    <td>@label.LabelId</td>
                                    <td>@label.LabelName</td>
                                      <td>
                                        <a asp-area="C_Area" asp-controller="Shops" asp-action="LabelEdit" asp-route-id="@label.LabelId" class="btn btn-info btn-sm">
                                            <i class="fas fa-edit"></i> Edit
                                            </a>
                                        <a asp-area="C_Area" asp-controller="Shops" asp-action="LabelDelete" asp-route-id="@label.LabelId" class="btn btn-danger btn-sm">
                                            <i class="fas fa-trash"></i> Delete
                                        </a>
                                    </td> 
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="createLabelModal" tabindex="-1" aria-labelledby="createLabelModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createLabelModalLabel">Create Label</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="createLabelForm" action="/C_Area/Shops/LabelCreate" asp-area="C_Area">
                @Html.AntiForgeryToken()
                <div class="modal-body">
                    <div class="form-group">
                        <label for="LabelName">Label Name</label>
                        <input type="text" id="LabelName" class="form-control" name="LabelName" placeholder="Enter label name" />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>

<script>
    $(document).ready(function () {
        $('#createLabelForm').on('submit', function (e) {
            e.preventDefault();
            alert("ok");
            var formData = new FormData(this);
            $.ajax({
                url: '@Url.Action("LabelCreate", "Shops", new { area = "C_Area" })',
                type: 'POST',
                data: formData,
                processData: false,
                contentType: false,
                success: function (response) {
                    if (response.success) {
                        $('#createLabelModal').modal('hide');
                    }
                },
                error: function (error) {
                    console.error(error);
                }
            });
        });
    });
</script>

Areas/C_Area/Views/Shops/ShopEdit.cshtml
@model C_Area.Areas.C_Area.ViewModel.ProductVM

@{
    ViewData["Title"] = "ShopIndex";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>ShopIndex</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form action="/C_Area/Shops/ShopEdit" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Name" class="control-label">Name</label>
                <input asp-for="Name" class="asp-form-control" name="Name" id="Name" />

            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Description</label>
                <input asp-for="Description" class="form-control" name="Description" id="Description" />

            </div>
            <div class="form-group">


                <div>
                    <input type="file" accept="image/*" onchange="readURL(this)" asp-for="UploadImage" class="form-control" name="UploadImage" id="UploadImage" />
                </div>
                <img id="img-preview" src="https://ami-sni.com/wp-content/themes/consultix/images/no-image-found-360x250.png" width="200px" />
            </div>


            <div class="form-group">
                <label asp-for="Price" class="control-label">Price</label>
                <input asp-for="Price" class="form-control" name="Price" id="Price" />

            </div>
            <div class="form-group">
                <label asp-for="LabelId" class="control-label">Label Id</label>
                <input asp-for="LabelId" class="form-control" name="LabelId" id="LabelId" />

            </div>

            <div class="form-group">
                <label asp-for="Category" class="control-label">Category</label>
                <input asp-for="Category" class="form-control" name="Category" id="Category" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="IsActive" class="control-label">Is Active</label>
                <select id="IsActive" class="form-control" name="IsActive">
                    <option value="true">Active</option>
                    <option value="false">Inactive</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


<script>
        //Change this to your no-image file
    let noimage =
      "https://ami-sni.com/wp-content/themes/consultix/images/no-image-found-360x250.png";

    function readURL(input) {
      console.log(input.files);
      if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
          $("#img-preview").attr("src", e.target.result);
        };

        reader.readAsDataURL(input.files[0]);
      } else {
        $("#img-preview").attr("src", noimage);
      }
    }

</script>

Areas/C_Area/Views/Shops/ShopIndex.cshtml
@model C_Area.Areas.C_Area.ViewModel.ProductVM

@{
    ViewData["Title"] = "ShopIndex";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>ShopIndex</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form action="/C_Area/Shops/ShopCreate" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Name" class="control-label">Name</label>
                <input asp-for="Name" class="asp-form-control" name="Name" id="Name" />
                
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Description</label>
                <input asp-for="Description" class="form-control" name="Description" id="Description" />
                
            </div>
            <div class="form-group">

               
                <div>
                    <input type="file" accept="image/*" onchange="readURL(this)" asp-for="UploadImage" class="form-control" name="UploadImage" id="UploadImage" />
                </div>
                <img id="img-preview" src="https://ami-sni.com/wp-content/themes/consultix/images/no-image-found-250x250.png" width="50%" ;/>
            </div>

           
            <div class="form-group">
                <label asp-for="Price" class="control-label">Price</label>
                <input asp-for="Price" class="form-control" name="Price" id="Price" />
            
            </div>

            <div class="form-group">
                <label for="LabelId" class="control-label">Label</label>
                <select id="LabelId" class="form-control" name="LabelId">
                    <option value="">---Select Label---</option>

                    @foreach (var labels in ViewBag.LabelList)
                    {
                        <option value="@labels.Value">@labels.Text</option>
                    }
                    
               </select>              
            </div>
           
            <div class="form-group">
                <label asp-for="Category" class="control-label">Category</label>
                <input asp-for="Category" class="form-control" name="Category" id="Category" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="IsActive" class="control-label">Is Active</label>
                <select id="IsActive" class="form-control" name="IsActive">
                    <option value="true">Active</option>
                    <option value="false">Inactive</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


<script>
        //Change this to your no-image file
    let noimage =
      "https://ami-sni.com/wp-content/themes/consultix/images/no-image-found-360x250.png";

    function readURL(input) {
      console.log(input.files);
      if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
          $("#img-preview").attr("src", e.target.result);
        };

        reader.readAsDataURL(input.files[0]);
      } else {
        $("#img-preview").attr("src", noimage);
      }
    }

</script>

Areas/C_Area/Views/Shops/ShopList.cshtml
@{
	ViewData["Title"] = "ShopList";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@model IEnumerable<C_Area.Areas.C_Area.Models.Product>


<!-- Default box -->
<div class="box">
	<div class="box-header with-border">
		<h3 class="box-title">Title</h3>
		<div class="box-tools pull-right">
			<button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
			<button class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove"><i class="fa fa-times"></i></button>
		</div>
	</div>
	<div class="box-body">


		<div class="container my-5">

			<table class="table table-hover my-5">
				<thead class="table-info">
					<tr>
						<th>Serial</th>
						<th>Name </th>
						<th>Description </th>
						<th>UploadImage</th>
						<th>Price</th>
						<th>LabelId</th>
						<th>Category</th>
						<th>IsActive</th>
						<th>Action</th>




					</tr>
				</thead>

				<tbody>
					@{
						int serial = 1;
						foreach (var data in Model)
						{
							<tr>
								<td>@serial</td>
								<td>@data.Name</td>
								<td>@data.Description</td>
								<td>
									<img src="~/Images/@data.Image" width="50%" />
								</td>
								<td>@data.Price</td>
								<td>@data.LabelId</td>
								<td>@data.Category</td>
								<td>@data.IsActive</td>



								<td>


									<a class="btn btn-info" asp-route-id="@data.ProductId" action="/C_Area/Shops/ShopInfo">ShopInfo</a>


									<a class="btn btn-warning" asp-route-id="@data.ProductId" action="/C_Area/Shops/ShopEdit">Edit</a>

									<a class="btn btn-danger" asp-route-id="@data.ProductId" action="/C_Area/Shops/Delete">Delete</a>


								</td>

							</tr>

							serial++;


						}



					}


				</tbody>


			</table>


		</div>

	</div><!-- /.box-body -->
	<div class="box-footer">
		Footer
	</div><!-- /.box-footer-->
</div><!-- /.box --> 

Views/Home/Admin.cshtml
@{
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h1>Welcome</h1>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_AdminMenus.cshtml
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->
        <li class="nav-item">
            <a href="#" class="nav-link">
                <i class="nav-icon fas fa-tachometer-alt"></i>
                <p>
                    Product
                    <i class="right fas fa-angle-left"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a asp-action="ShopIndex" asp-controller="Shops" asp-area="C_Area" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Shop Create</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-area="C_Area" asp-controller="Shops" asp-action="ShopList" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>ShopList</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-area="C_Area" asp-controller="Shops" asp-action="Labels" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Label List</p>
                    </a>
                </li>

            </ul>
        </li>


        <li class="nav-item">
            <a asp-action="SocialNetwork" asp-controller="SocialLinks" class="nav-link">
                <i class="nav-icon far fa-image"></i>
                <p>
                    Social Network
                </p>
            </a>
        </li>
    </ul>
</nav>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - C_Area</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/C_Area.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">C_Area</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Admin">Admin</a>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - C_Area - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>